config/routes.rb
SearchWordCreator::Application.routes.draw do
  resources :users, except: [:index, :show, :destroy]
  resources :word_search_puzzles do
    member do
      get 'new/', :action => 'new', as: 'new_promo'
    end
  end 
  resources :sessions, only: [:new, :create, :destroy]

  match '/download/:file_name', to: 'word_search_puzzles#download', as: "download"

  match "/purchase", to: "subscriptions#new", as: "purchase", via: :get
  match "/purchase", to: "subscriptions#create", as: "purchase", via: :post
  match "/purchase", to: "subscriptions#create", as: "purchase", via: :put

  match "/ask-us-pricing", to: "static_pages#ask_us_pricing", :as => "ask_us_pricing"
  match '/faq', to: 'static_pages#faq'
  match "/contact", to: "static_pages#contact"
  match "/plans-and-pricing" => "static_pages#plans", :as => "plans"
 
  match '/print', to: 'word_search_puzzles#print'
  match '/word-search-puzzles/:category/:name', to: 'word_search_puzzles#promo_puzzle', as: "promo_puzzle"
  match '/word-search-puzzles/:category', to: 'word_search_puzzles#category', as: "category"
  match '/word-search-puzzles', to: 'word_search_puzzles#index', as: 'index'

  match "/dashboard", to: "users#dashboard"
  match '/signup', to: 'users#new'

  match '/signin', to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete

  root :to => 'static_pages#home'

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def contact
  end

  def faq
  end

  def home
  end

  def plans
  end

  def purchase
  end

  def ask_us_pricing
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/contact.html.erb
<% provide(:title, 'Contact Search Word Creator') %>
<% provide(:meta_description, "Contact Search Word Creator with your questions or comments.") %>
<% provide(:meta_keywords, 'search word creator, contact, support') %>
<% provide(:page_type, 'page') %>
<% content_for :mixpanel_tracking do %>
	<script type="text/javascript">
  	  $(document).ready( function(){
        mixpanel.track("Seeing Contact Page");
        mixpanel.track_links(".contact-email-link", "Clicked on 'email us' link" );
      });
   </script>
<% end %>
<% content_for :sidebar do %>
  <div class="contacts right">
		<div>
			<div>					
				<div>
					<h3>Have a Question?</h3>
					<p>
						It's probably already answered!
					</p>
					<br/>
					<p>
						Check out the <%= link_to "FAQ", faq_path %>.
					</p>
				</div>				
			</div>
		</div>
	</div>
<% end %>

<div class="contactForm radius">
	<h3>Send Us an Email</h3>
	<p> 
		We're always happy to hear from our customers at Search Word Creator if you have a question, a problem, or if you just want to talk about using word search to teach in your classroom. You can send us an <%= link_to "email", "mailto:support@searchwordcreator.com", class: "contact-email-link" %> at any time. We'll do our best to get back to you within 24 hours. If you're not a customer yet but are having problems with our free trial, please don't hesitate to send an email.
	</p>
	<!-- Maybe put this back in one day .. 
	<div class="wpcf7" id="wpcf7-f1-p18-o1">
	<form action="#" method="post" class="wpcf7-form">
		<div class="half left">
    				<label>Your Name</label><span class="wpcf7-form-control-wrap your-name"><input type="text" name="your-name" value="" class="wpcf7-validates-as-required" size="40" /></span>
  			</div>
		<div class="half right">
   				<label>Your E-mail Address</label><span class="wpcf7-form-control-wrap your-email"><input type="text" name="your-email" value="" class="wpcf7-validates-as-email wpcf7-validates-as-required" size="40" /></span>
  			</div>
		<div class="item">
    				<label>Your Message</label><span class="wpcf7-form-control-wrap your-message"><textarea name="your-message" cols="40" rows="10"></textarea></span>
  			</div>
		<div class="item a-right">
   				<input type="submit" value="Send Message" />
  			</div>
		<div class="wpcf7-response-output wpcf7-display-none"></div>
	</form>
	</div>

	... end comment -->
	
</div>

app/views/static_pages/faq.html.erb
<% provide(:title, 'FAQ') %>
<% provide(:meta_description, "Frequently asked questions about Search Word Creator") %>
<% provide(:meta_keywords, 'faq, frequently asked questions, search word creator') %>
<% provide(:page_type, 'page') %>
<% content_for :mixpanel_tracking do %>
	<script type="text/javascript">
  	  $(document).ready( function(){
        mixpanel.track("Seeing FAQ Page");
      });
   </script>
<% end %>
<% content_for :sidebar do %>
	<div class="contacts right">
		<div>
			<div>					
				<div>
					<h3>Need our help?</h3>
					<p>
						We welcome all emails from customers needing support, or people with questions about the Word Search Creator.
					</p>
					<br/>
					<p>
						Check out the <%= link_to "Contact Page", contact_path %>.
					</p>
				</div>				
			</div>
		</div>
	</div>
<% end %>

<div class="post">
	<div class="entry">
		<p>We're always happy to hear from our customers at Search Word Creator if you have a question, a problem, or if you just want to talk about using word search to teach in your classroom. You can send us an <%= link_to "email", "mailto:support@searchwordcreator.com" %> at any time. We'll do our best to get back to you within 24 hours. If you're not a customer yet but are having problems with our free trial, please don't hesitate to send an email.</p>

		<h3>Q: What is a Search Word Puzzle?</h3>
		<h4>A: Search Word Puzzles, also known as Word Search Puzzles or Word Find Puzzles, are a fun puzzle that can be used to learn vocabulary words.</h4>
		<br/>
		<h3>Q: What is a Search Word Creator?</h3>
		<h4>A: Search Word Creator is a software that easily makes seaarch word puzzles.  Some people think of it as a Search Word Maker, Search Word Generator, Word Search Maker, Word Search Creator, or Word Search Generator.  Whew, that's a mouthful!</h4>
	</div>
</div>

app/views/static_pages/home.html.erb
<% provide(:title, 'Create custom printable search word puzzles') %>
<% provide(:meta_description, "Create and print your own custom word search puzzles on your Windows PC or Mac.  You can try it free today!") %>
<% provide(:meta_keywords, 'esl, teaching activity, tefl, search word creator, word search creator, word find creator, search word puzzle, word search puzzle, word find puzzle, teaching, activities, teaching activity, printable, print, printing') %>
<% provide(:page_type, 'home') %>
<% content_for :mixpanel_tracking do %>
	<script type="text/javascript">
  	  $(document).ready( function(){
        mixpanel.track("Seeing Home Page");
      });
   </script>
<% end %>


	<!-- div start center -->
	<div class="center">
		<!-- div start proms -->
		<div class="proms">
			<div class="left">
				<h1>Create Your Own<br/>Word Search Right Now!</h1>
				<p>Teachers and parents use <strong>Search Word Creator</strong> to make custom, <strong>printable</strong> puzzles for learning and playing.</p>
		
				<%= link_to "Start Making Puzzles", new_word_search_puzzle_path, class: "radius button" %>
				<p>Free Trial. 30 Day Money Back Guarantee</p>
			</div>
			<div class="right">
				<img src="assets/screenshots.png" alt="Search Word Creator Screenshots" />
			</div>
		</div>
		<!-- div end proms -->
		<!-- div start features -->
		<div class="features">
			<ul>		
				<li>
					<div class="icon">
						<img src="assets/saas-images/i_clock.png" alt="Save Time" />
					</div>
					<div class="content">
						<h3>Save Time</h3>
						<p>You can use <strong>Search Word Creator</strong> to <strong>print</strong> puzzles for an entire classroom on your normal computer and printer in mere minutes. Finding puzzles takes hours -- hours that you could better spend teaching.</p>
					</div>
				</li>
				<li>
					<div class="icon">
						<img src="assets/saas-images/i_wallet.png" alt="Save Money" />
					</div>
					<div class="content">
						<h3>Save Money</h3>
						<p>Don't spend $10-$15 on buying single activities from traditional publishers! If you use word search three times or more in a year, it's much cheaper to print your own puzzles using <strong>Search Word Creator</strong>!</p>
					</div>
				</li>
				<li>
					<div class="icon">
						<img src="assets/saas-images/i_print.png" alt="Custom Activities" />
					</div>
					<div class="content">
						<h3>Custom Activities</h3>
						<p> Play vocabulary search word from the chapter you just finished!  With <strong>Search Word Creator</strong> you can tailor your puzzles to your lesson plan. If you buy search word puzzles from publishers, you're limited to what they have in stock.</p>
					</div>
				</li>
				<li>
					<div class="icon">
						<img src="assets/saas-images/i_shield.png" alt="Buy With Confidence" />
					</div>
					<div class="content">
						<h3>Buy With Confidence</h3>
						<p>You get a free trial to see if <strong>Search Word Creator</strong> is perfect for you and your lesson plans.  We offer an unconditional 30 day money-back guarantee.  If you're not happy with our software, we don't deserve your business.</p>
					</div>
				</li>	
			</ul>
		</div>
		<!-- div end features -->
		<!-- div start testimonials -->
		<div class="testimonials radius">
			<div>		
				<h3>What Teachers Are Saying</h3>
				<ul>
					<li>
						<div class="avatar"><img src="assets/saas-images/avatar.png" alt="" /></div>
						<div class="testiContent">
							<div class="radius">
								<span class="arrow"><img src="assets/saas-images/bg-arrow.png" alt="" /></span>
								<p><strong>Word searches</strong> are useful to help students build stamina and help with learning to key in on details. I use word searches to help my students learn that you look everywhere to help find information.</p>
								<p class="a-right"><em>Rhonda, <strong>Elemetary School Teacher</strong></em></p>
							</div>
						</div>
					</li>
				</ul>	
			</div>
		</div>
		<!-- div end testimonials -->
		<!-- div start free trial -->
		<div class="free-trial radius">
			<h3>Free Trial</h3>
			<%= link_to "Make Puzzles Now!", signup_path, class: "radius button" %>
			<p>Takes 15 seconds</p>
		</div>
		<!-- div end free trial -->
	</div>
	<!-- div end center -->

app/views/static_pages/plans.html.erb
<% provide(:title, 'Plans and Pricing') %>
<% content_for :mixpanel_tracking do %>
	<script type="text/javascript">
      $(document).ready( function(){
        mixpanel.track("Seeing Plans and Pricing Page");
        mixpanel.track_links(".free-trial-btn.btn", "Clicked on link to start free trial" );
        mixpanel.track_links(".ask-us-btn.btn", "Clicked on link to ask about premier pricing" );
        mixpanel.track_links(".purchase-btn.btn", "Clicked on link to purchase now" );
      });
   </script>
<% end %>
<% provide(:page_type, 'page plans') %>
	<div class="center">				
		<h1 style="text-align: center;">100% Money Back Guarantee</h1>
		<h4 style="text-align: center;">If you aren't completely satisfied, we will even pay for the transaction fee for you!</h4>
		<br/>
		<br/>
		<div class="features">
			<ul>
			<li>
				<div class="icon">
					<img src="assets/saas-images/i_clock.png" alt="Use Immediately" />
				</div>
				<div class="content">
					<h3>Use Immediately</h3>
					<p>As soon as you sign up, you can use the software within seconds.  There is nothing more to download if you are already using the trial version.</p>
				</div>
			</li>
			<li>
				<div class="icon">
					<img src="assets/saas-images/i_wallet.png" alt="Pay with Credit Card" />
				</div>
				<div class="content">
					<h3>Pay with Credit Card</h3>
					<p>We accept Visa, Mastercard, American Express and Discover.  No international payments are accepted (yet!).</p>
				</div>
			</li>
			<li>
				<div class="icon">
					<img src="assets/saas-images/i_up.png" alt="Updates Included" />
				</div>
				<div class="content">
					<h3>Updates Included</h3>
					<p>Whenever new features are released to search word creator, you get immediate access as a paid member.</p>
				</div>
			</li>
			<li>
				<div class="icon">
					<img src="assets/saas-images/i_shield.png" alt="Money Back Guarantee" />
				</div>
				<div class="content">
					<h3>Money Back Guarantee</h3>
					<p>Change your mind any time within 30 days and we will give you a refund of everything you've paid so far, without hassling you.</p>
				</div>
			</li>
			</ul>
		</div>
	</div>