config/routes.rb
SearchWordCreator::Application.routes.draw do
  resources :users, except: [:index, :show, :destroy]
  resources :word_search_puzzles do
    member do
      get 'new/', :action => 'new', as: 'new_promo'
    end
  end 
  resources :sessions, only: [:new, :create, :destroy]

  match '/download/:file_name', to: 'word_search_puzzles#download', as: "download"

  match "/purchase", to: "subscriptions#new", as: "purchase", via: :get
  match "/purchase", to: "subscriptions#create", as: "purchase", via: :post
  match "/purchase", to: "subscriptions#create", as: "purchase", via: :put

  match "/ask-us-pricing", to: "static_pages#ask_us_pricing", :as => "ask_us_pricing"
  match '/faq', to: 'static_pages#faq'
  match "/contact", to: "static_pages#contact"
  match "/plans-and-pricing" => "static_pages#plans", :as => "plans"
 
  match '/print', to: 'word_search_puzzles#print'
  match '/word-search-puzzles/:category/:name', to: 'word_search_puzzles#promo_puzzle', as: "promo_puzzle"
  match '/word-search-puzzles/:category', to: 'word_search_puzzles#category', as: "category"
  match '/word-search-puzzles', to: 'word_search_puzzles#index', as: 'index'

  match "/dashboard", to: "users#dashboard"
  match '/signup', to: 'users#new'

  match '/signin', to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete

  root :to => 'static_pages#home'

end

app/models/word_search_puzzle.rb
# == Schema Information
#
# Table name: word_search_puzzles
#
#  id            :integer          not null, primary key
#  name          :string(255)      default("New Puzzle 11-19-2012  2:08 pm"), not null
#  times_printed :integer          default(0), not null
#  words         :text             default(""), not null
#  created_at    :datetime         not null
#  updated_at    :datetime         not null
#  grid_width    :integer          default(18)
#  grid_height   :integer          default(18)
#  user_id       :integer
#  category      :string(255)      default("")
#

class WordSearchPuzzle < ActiveRecord::Base
	VALID_WORD_REGEX = /\A[A-Z a-z-]+\z/

	belongs_to :user

  serialize :words, Array
  attr_accessible :name, :words, :grid_width, :grid_height

  before_validation :sanitize_words
	before_save { self.category = "" if self.category.nil? }

	validates :category, length: { maximum: 255 }
  validates :name, presence: true, length: { maximum: 50 }
  validates :grid_width, presence: true, numericality: { greater_than: 5, less_than: 19 }
  validates :grid_height, presence: true, numericality: { greater_than: 5, less_than: 19 }

  validates_each :words do |record, attr, words|
  	problems = ''
  	if !words.empty?
			words.each do |word|
				word = word.gsub(/\s+/, "") # strip out all whitespace
				word = word.gsub(/-+/, "") # strip out all hyphens
				if word.scan(VALID_WORD_REGEX).empty?
					problems << "can only contain letters, spaces and hyphens."
				elsif !record.grid_height.nil? && !record.grid_width.nil? &&
					    (word.length > record.grid_height || word.length > record.grid_width)
					problems << "#{word} is too long for a puzzle of this size.\n"
				end
			end
  	else
			problems = 'At least one word is required.'
			record.words = '' #Reset words for viewing purposes.
  	end
  	if problems != ''
  		record.errors.add(:words, problems)
  	end
  end	

	private
		def sanitize_words
			self.words = [] if self.words.empty?
			self.words.each do |word|
				word.upcase!
				word.strip!
			end
			self.words.delete_if{ |word| word.blank? }
		end
end

app/controllers/word_search_puzzles_controller.rb
class WordSearchPuzzlesController < ApplicationController 
  before_filter :signed_in_user, only: [:new, :edit, :create, :destroy, :print, :download]
  before_filter :blocked_trial_user, only: [:new, :edit, :create, :destroy, :print, :download]
  
  def new
    @word_search_puzzle = WordSearchPuzzle.new
    @word_search_puzzle = WordSearchPuzzle.find(params[:id]).dup unless params[:id].nil?
    unless @word_search_puzzle.words.blank?
      words_string = ""
      @word_search_puzzle.words.each do |word|
        words_string += "#{word}\r\n"
      end
      @word_search_puzzle.words = words_string
    end
    render 'new'
  end

  def edit
  end

  def create
  	grid_size = 18
    @words = params[:word_search_puzzle][:words].split("\r\n")
    @word_search_puzzle = WordSearchPuzzle.new(
  	                         name: params[:word_search_puzzle][:name],
														 words: @words,
														 grid_width: grid_size,
														 grid_height: grid_size)
 		unless @word_search_puzzle.save
      @words = @words.join("\r\n")
      render 'new'
    end
  end

  def destroy
  end

  def print
    loaded_params = params
    unless session[:params].nil?
      loaded_params = YAML::load(session[:params]) 
      session[:params] = nil
    end
    logger.debug "PARAMS: #{params}"
    logger.debug "SESSPARAMS: #{session[:params]}"
    logger.debug "LOADED PARAMS: #{loaded_params}"
  	grid_size = 18
    num_puzzles_printed = Integer(loaded_params[:num_puzzles])
		@word_search_puzzle = WordSearchPuzzle.find(loaded_params[:word_search_puzzle_id])
    @word_search_puzzle.user = current_user
    @word_search_puzzle.times_printed += num_puzzles_printed
    # Note: saving subscription updates the puzzle count for the user
    if @word_search_puzzle.save && current_user.subscription.save
  		pdf = SearchWordDocument.new(words: @word_search_puzzle.words,
                                   puzzle_grid_size: grid_size)
      @file_name = pdf.generate_pdf(num_puzzles_printed,
  																	current_user.name)
    end
    @puzzle_count = WordSearchPuzzle.where("category <> ''").count
    @puzzles_category_count = WordSearchPuzzle.select("DISTINCT(CATEGORY)").count - 1 #subtract out category of ""

  end

  def download
    send_file "#{Rails.root.to_s}/tmp/#{params[:file_name]}.pdf"
  end

  def promo_puzzle
    @category = params[:category]
    @puzzle_name = params[:name].link_to_category
    @word_search_puzzle = WordSearchPuzzle.find_by_category_and_name(@category.link_to_category, @puzzle_name)
    @puzzle_count = WordSearchPuzzle.where("category <> ''").count
    @puzzles_category_count = WordSearchPuzzle.select("DISTINCT(CATEGORY)").count - 1 #subtract out category of ""
  end

  def index
    puzzles_with_category = WordSearchPuzzle.select("DISTINCT(CATEGORY)")
    # Delete the category of puzzles that have no category (that is, user created)
    puzzles_with_category.delete_if { |puzzle| puzzle.category == "" }
    puzzles_with_category.sort! { |a,b| a.category <=> b.category }

    @puzzle_count = WordSearchPuzzle.where("category <> ''").count
    @puzzle_categories = []
    puzzles_with_category.each do |puzzle|
      puzzle_category = { name: puzzle.category, 
                           count: WordSearchPuzzle.where(:category => puzzle.category).count
                         }
      @puzzle_categories.push(puzzle_category)
    end
  end

  def category
    @category = params[:category]
    @puzzles = WordSearchPuzzle.find_all_by_category(@category.link_to_category)
    @puzzles = @puzzles.sort! { |a,b| a.name <=> b.name }
    @puzzle_count = WordSearchPuzzle.where("category <> ''").count
    @puzzles_category_count = WordSearchPuzzle.select("DISTINCT(CATEGORY)").count - 1 #subtract out category of ""
  end

  private
    def blocked_trial_user
      render 'blocked' if signed_in? && !current_user.subscription.paid_user? && !current_user.subscription.trial_user?
    end
end

app/helpers/word_search_puzzles_helper.rb
module WordSearchPuzzlesHelper
end

app/views/word_search_puzzles/blocked.html.erb
<% provide(:title, 'Create custom search word puzzles with Search Word Creator') %>
<% provide(:page_type, 'page') %>
<% content_for :mixpanel_tracking do %>
	<script type="text/javascript">
  	  $(document).ready( function(){
        mixpanel.track("Blocked due to Trial Expiration");
        mixpanel.people.increment("Blocked Because of Trial Limit");
      });
   </script>
<% end %>

<div class="alert alert-error">
	<h3>Your trial has expired...</h3>
	<br/>
	<br/>
	<p>You printed out all of the puzzles that the trial period allows.  You can <%= link_to "upgrade right now", purchase_path %> to continue making puzzles.</p>
	<br/>
</div>

<div class="alert alert-success">
	<h1>You can upgrade!</h1>
	<br/>
	<br/>
	<p>You can <%= link_to "upgrade right now", purchase_path %> to continue making puzzles.</p>
	<br/>
</div>

<div class="alert alert-info">
	<h3>Don't want to upgrade?</h3>
	<br/>
	<br/>
	<p>Can you take 30 seconds to <%= link_to "send us an email", "mailto:support@searchwordcreator.com" %> and let us know why you will not be upgrading?</p>
	<br/>
</div>

app/views/word_search_puzzles/category.html.erb
<% provide(:title, "#{@category.link_to_category} search word puzzles") %>
<% provide(:page_type, 'page') %>
<% provide(:meta_description, "#{@puzzles.count} free, printable word search #{"puzzle".pluralize(@puzzles.count)} available for #{@category.link_to_category} for ESL teachers.") %>
<% provide(:meta_keywords, "#{@category.link_to_category}, esl, teaching activity, tefl, search word creator, word search creator, word find creator, search word puzzle, word search puzzle, word find puzzle, teaching, activities, teaching activity, printable, print, printing") %>
<% content_for :mixpanel_tracking do %>
	<script type="text/javascript">
  	  $(document).ready( function(){
        mixpanel.track("Seeing Category Page", { 'category': "<%= @category.capitalize %>"});
      });
  </script>
<% end %>
<% content_for :sidebar do %>
	<div id="sidebar" class="col-side left">
		<div class="widget">
			<h2>Get Started!</h2>
			<ul>
				<li>
					<p>
						Start using Search Word Creator to Create your own <strong>printable search word puzzles.</strong>
					</p>
				</li>
			</ul>
		</div>
	</div>
<% end %>

<h1><%= @category.link_to_category.titlecase %> Search Word Puzzles</h1>
<p>Below are the <strong>word search puzzles</strong> that are available for <%= @category.link_to_category.titlecase %>.  Click on any puzzle to get started <strong>creating a custom, printable search word puzzle</strong> from this word list within 15 seconds! </p>
<br/>
<div class="alert alert-info">
	<h3 style="text-align: center;">We have <%= pluralize(@puzzle_count, "puzzle") %> in <%= pluralize(@puzzles_category_count, "category") %>!</h3>
	<br/>
	<p>Don't like anything in this category?  Go to the <%= link_to "main index", word_search_puzzles_path %> to see all <%= pluralize(@puzzles_category_count, "category") %> from which you can choose!</p>
	<br/>
</div>

<div class="promo-row">
<% @puzzles.each_with_index do |puzzle, index| %>
	<% if index % 3 == 0 && index != 0 %>
	</div>
	<div class="promo-row">
	<% end %>
	<%= link_to puzzle.name, promo_puzzle_path(@category, puzzle.name.category_to_link ) %>
<% end %>
</div>

app/views/word_search_puzzles/create.html.erb
<% provide(:title, 'Create custom search word puzzles with Search Word Creator') %>
<% provide(:page_type, 'page') %>
<% content_for :mixpanel_tracking do %>
	<script type="text/javascript">
  	  $(document).ready( function(){
        mixpanel.track("Seeing Configure Puzzle Page");
        mixpanel.track_forms("#configure-puzzle", "Configure Puzzle Form Submission", 
        	function(form) { return { "Puzzles printed": $("#configure-puzzle #num_puzzles").val() };
        });
      });
   </script>
<% end %>
<% content_for :sidebar do %>
<div id="sidebar" class="col-side left">
	<div class="widget">
		<h2>Step 2 of 3</h2>
		<ul>
			<li>
				<p>
					All printed puzzles will be different!
				</p>
				<br/>
				<p>
					Each puzzle will be printed with its solutions.
				</p>
				<br/>
				<p>
					Scroll down for a list of all of the words you added.  Remember, not all of the words you added will appear in the puzzle, since word search puzzles have limited space!
				</p>
			</li>
		</ul>
	</div>
</div>
<% end %>
<%= form_tag print_path, id: "configure-puzzle" do%>
	<li>
  <%= label_tag "Total Number of Puzzles" %>
  <%= text_field_tag :num_puzzles, "5" %>
	</li>
	<%= hidden_field_tag :word_search_puzzle_id, @word_search_puzzle.id %>

  <%= submit_tag "Print Puzzles", class: "btn btn-large btn-primary" %>
</ul>
<% end %>
<div class="added-words">
	<h1>Words You've Added</h1>
		<div class="entry">
			<ul>
			  <% @words.each do |word| %>
					<li><%=  word %></li>
				<% end %>
			</ul>
	</div>
</div>
<%= debug(@word_search_puzzle) if Rails.env.development? %>

app/views/word_search_puzzles/index.html.erb
<% provide(:title, "Free printable search word puzzles") %>
<% provide(:page_type, 'page') %>
<% provide(:meta_description, "Over #{@puzzle_count} free, printable word search puzzles available in #{@puzzle_categories.count} categories for ESL teachers.") %>
<% provide(:meta_keywords, 'esl, teaching activity, tefl, search word creator, word search creator, word find creator, search word puzzle, word search puzzle, word find puzzle, teaching, activities, teaching activity, printable, print, printing') %>
<% content_for :mixpanel_tracking do %>
	<script type="text/javascript">
  	  $(document).ready( function(){
        mixpanel.track("Seeing Word Search Puzzle List"});
      });
  </script>
<% end %>
<% content_for :sidebar do %>
	<div id="sidebar" class="col-side left">
		<div class="widget">
			<h2>Get Started!</h2>
			<ul>
				<li>
					<p>
						Start using Search Word Creator to Create your own <strong>printable search word puzzles.</strong>
					</p>
				</li>
			</ul>
		</div>
	</div>
<% end %>

<h1>Free Printable Search Word Puzzles</h1>
<br/>
<p><strong>Search Word Creator</strong> lets you create and customize <strong>printable word search puzzles</strong>.  Below are the categories of puzzles that we created for you.</p>
<br/>
<p>Click on the category below to see the available pre-made puzzles, ready for printing and using within seconds!</p>
<br/>

<div class="alert alert-info">
	<h3 style="text-align: center;">We have <%= pluralize(@puzzle_count, "puzzle") %> in <%= pluralize(@puzzle_categories.count, "category") %>!</h3>
</div>

<div class="promo-row">
<% @puzzle_categories.each_with_index do |category, index| %>
	<% if index % 3 == 0 && index != 0 %>
	</div>
	<div class="promo-row">
	<% end %>
	<%= link_to category_path(category[:name].category_to_link), class: "category" do %>
		<%= category[:name] %> 
		<span class="puzzle-count"><%= pluralize(category[:count], 'puzzle') %> </span>
	<% end %>
<% end %>
</div>

app/views/word_search_puzzles/new.html.erb
<% provide(:title, 'Create custom search word puzzles with Search Word Creator') %>
<% provide(:page_type, 'page') %>
<% content_for :mixpanel_tracking do %>
	<script type="text/javascript">
  	  $(document).ready( function(){
        mixpanel.track("Seeing New Word Search Puzzle Page");
        mixpanel.track_forms("#new_word_search_puzzle", "New Puzzle Form Submission");
      });
  </script>
<% end %>
<% content_for :sidebar do %>
	<div id="sidebar" class="col-side left">
		<div class="widget">
			<h2>Step 1 of 3</h2>
			<ul>
				<li>
					<p>
						Type the words you want to use into the box, one per line.  Then click on "Next Step" to move on.
					</p>
					<br/>
					<p>
						Every puzzle will be different.  Words can only be 18 letters long.  Spaces and dashes are ok - but <em>no symbols or numbers</em>!  If the word has a space or a dash, the space will be removed on the puzzle.
					</p>
					<br/>
					<p>
						A word list can have as many words as you want, but not all of them may make it onto every puzzle, since each puzzle has limited space.
					</p>
				</li>
			</ul>
		</div>
	</div>
<% end %>

<%= form_for(@word_search_puzzle) do |f| %>
	<%= render 'shared/error_messages', object: f.object %>
	<ul>
		<li>
      <%= f.label :name %>
			<%= f.text_field :name %>
		</li>
		<li>
			<%= f.label :words %>
			<%= f.text_area :words, value: @words %>
		<li>
	</ul>
  <%= f.submit "Next Step", class: "btn btn-large btn-primary" %>
<% end %>

<%= image_tag "puzzle_sample.png", class:"sample-image"  %>

app/views/word_search_puzzles/print.html.erb
<% provide(:title, 'Create custom search word puzzles with Search Word Creator') %>
<% provide(:page_type, 'page') %>
<% content_for :mixpanel_tracking do %>
	<script type="text/javascript">
			$(document).ready( function(){
        mixpanel.track("Seeing Print Puzzles Page");
        mixpanel.track_links(".download-puzzles-link", "Clicked Link to Download Puzzles", 
        	function(ele) { 
        		mixpanel.people.increment("Downloaded Puzzle PDFs")
        		return { }
        	}
        );
      });
   </script>
<% end %>
<% content_for :sidebar do %>
<div id="sidebar" class="col-side left">
	<div class="widget">
		<h2>Step 3 of 3</h2>
		<ul>
			<li>
				<p>
					You're almost done!
				</p>
				<br/>
				<p>
					After you download your puzzles, you can open them and print them out.
				</p>
				<br/>
				<p>
					99% of computers can open these files immediately.  If you can't, you may need to download Adobe Reader.  You can <a href="http://get.adobe.com/reader/">get it here</a>.
				</p>
			</li>
		</ul>
	</div>
</div>
<% end %>


<%if current_user.first_login? %>
	<!-- Google Code for User Signup Conversion Page -->
	<script type="text/javascript">
		/* <![CDATA[ */
		var google_conversion_id = 1004188671;
		var google_conversion_language = "en";
		var google_conversion_format = "3";
		var google_conversion_color = "ffffff";
		var google_conversion_label = "sDyCCLH38AUQ_-fq3gM";
		var google_conversion_value = 0;
		/* ]]> */
	</script>
	<script type="text/javascript" src="http://www.googleadservices.com/pagead/conversion.js">
	</script>
	<noscript>
		<div style="display:inline;">
			<img height="1" width="1" style="border-style:none;" alt="" src="http://www.googleadservices.com/pagead/conversion/1004188671/?value=0&amp;label=sDyCCLH38AUQ_-fq3gM&amp;guid=ON&amp;script=0"/>
		</div>
	</noscript>
<% end %>
<h1>Ready to download!</h1>
<br/>
<p>Your puzzles are ready to download!  Click the huge button below to download your puzzles now.  Once downloaded, open them and then print!</p>
<%= link_to "Download Your Puzzles!", download_path(@file_name), class: "download-puzzles-link" %>
	
<div class="alert alert-nofity">
	<h1>Want more ready-made puzzles?</h1>
	<br/>
	<p>We have <%= pluralize(@puzzle_count, "puzzle") %> in <%= pluralize(@puzzles_category_count, "category") %>!  Go to the <%= link_to "main index", word_search_puzzles_path %> to see them all!</p>
</div>
<div class="alert alert-info">
	<h1>Want to make more of your own?</h1>
	<br/>
	<p>Just <%= link_to "click here", new_word_search_puzzle_path %> to start again and enter all of your own words for a custom set of puzzle!</p>
</div>

app/views/word_search_puzzles/promo_puzzle.html.erb
<% provide(:title, "#{@puzzle_name.titlecase} search word puzzles") %>
<% provide(:page_type, 'page') %>

<% meta_desc = "" %>
<% @word_search_puzzle.words.each_with_index do |word, index| 
	break if index == 4	%>
	<% if index == 3 || index == @word_search_puzzle.words.length-2 %>
		<% meta_desc += "and #{word.titlecase}." %>
	<% else %>
		<% meta_desc += "#{word.titlecase}, " %>
	<% end %>
<% end %></p>

<% provide(:meta_description, "A free, printable #{@puzzle_name.titlecase} word search puzzle for ESL teachers, including the words #{meta_desc}. Useful for teaching about #{@category.link_to_category}.") %>
<% provide(:meta_keywords, "#{@category.link_to_category}, #{@puzzle_name.titlecase}, esl, teaching activity, tefl, search word creator, word search creator, word find creator, search word puzzle, word search puzzle, word find puzzle, teaching, activities, teaching activity, printable, print, printing") %>
<% content_for :mixpanel_tracking do %>
	<script type="text/javascript">
  	  $(document).ready( function(){
        mixpanel.track("Seeing Promo Page", { 'promo puzzle': "<%= @puzzle_name %>"});
      });
  </script>
<% end %>
<% content_for :sidebar do %>
	<div id="sidebar" class="col-side left">
		<div class="widget">
			<h2>Get Started!</h2>
			<ul>
				<li>
					<p>
						Start using Search Word Creator to Create your own <strong>printable search word puzzles.</strong>
					</p>
				</li>
			</ul>
		</div>
	</div>
<% end %>

<h1><%= @puzzle_name %> Search Word Puzzles</h1>
<br/>
<img class="promo-img" src="/assets/puzzle.png" alt="Sample Puzzle"/>
<div class="promo-text">
	<p>These puzzles are about <strong><%= @puzzle_name %></strong>.</p>
	<br/>
	<p>These are some common words or names associated with <strong><%= @puzzle_name %></strong>. These include words like 
	<% @word_search_puzzle.words.each_with_index do |word, index| 
		break if index == 4	%>
		<% if index == 3 || index == @word_search_puzzle.words.length-2 %>
			and <em><%= "#{word.titlecase}." %></em>
		<% else %>
			<em><%= "#{word.titlecase}," %></em>
		<% end %>
	<% end %></p>
	<br/>
	<p>You can create puzzles like these using <strong>Search Word Creator</strong>. You can try it, totally free, for up to 15 puzzles.</p>
	<%= link_to "Print Puzzles", new_promo_word_search_puzzle_path(@word_search_puzzle), class: "promo-print-btn"%>
	<div class="alert alert-info">
		<h3 style="text-align: center;">We have <%= pluralize(@puzzle_count, "puzzle") %> in <%= pluralize(@puzzles_category_count, "category") %>!</h3>
		<br/>
		<p style="text-align: center;">Go to the <%= link_to "main index", word_search_puzzles_path %> to see all <%= pluralize(@puzzles_category_count, "category") %>!</p>
	</div>
</div>