config/routes.rb
SearchWordCreator::Application.routes.draw do
  resources :users, except: [:index, :show, :destroy]
  resources :word_search_puzzles do
    member do
      get 'new/', :action => 'new', as: 'new_promo'
    end
  end 
  resources :sessions, only: [:new, :create, :destroy]

  match '/download/:file_name', to: 'word_search_puzzles#download', as: "download"

  match "/purchase", to: "subscriptions#new", as: "purchase", via: :get
  match "/purchase", to: "subscriptions#create", as: "purchase", via: :post
  match "/purchase", to: "subscriptions#create", as: "purchase", via: :put

  match "/ask-us-pricing", to: "static_pages#ask_us_pricing", :as => "ask_us_pricing"
  match '/faq', to: 'static_pages#faq'
  match "/contact", to: "static_pages#contact"
  match "/plans-and-pricing" => "static_pages#plans", :as => "plans"
 
  match '/print', to: 'word_search_puzzles#print'
  match '/word-search-puzzles/:category/:name', to: 'word_search_puzzles#promo_puzzle', as: "promo_puzzle"
  match '/word-search-puzzles/:category', to: 'word_search_puzzles#category', as: "category"
  match '/word-search-puzzles', to: 'word_search_puzzles#index', as: 'index'

  match "/dashboard", to: "users#dashboard"
  match '/signup', to: 'users#new'

  match '/signin', to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete

  root :to => 'static_pages#home'

end

app/views/layouts/_footer.html.erb
<div class="footer">
	<div>
		<div class="center">
			<p>
		    Copyright © 2012 Christopher Salvato.
			</p>
			<%= debug(["PARAMS", params]) if Rails.env.development? %>
			<%= debug(["SESSION", session]) if Rails.env.development? %>
			<%= debug([request.remote_ip.inspect, request.request_method.inspect]) if Rails.env.development? %> 
			<%= debug([current_user, current_user.subscription]) if Rails.env.development? && signed_in? %>
		</div>
	</div>
</div>
<!--div.footer end -->

app/views/layouts/_google_analytics.html.erb
<% if Rails.env.production? %>
		<script type="text/javascript">
		  var _gaq = _gaq || [];
		  _gaq.push(['_setAccount', 'UA-36554471-1']);
		  _gaq.push(['_trackPageview']);

		  (function() {
		    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
		    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
		    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
		  })();

		</script>
	<% end %>

app/views/layouts/_header.html.erb
<div class="header">
	<div>
    	<div>
			<div class="center">
				<h1 class="logo"><%= link_to image_tag("saas-images/logo.png", alt: "Search Word Creator"), root_path%></h1>
				<div class="header-right">
					<div class="topnav">
						<ul id="menu-top-links" class="menu">
							<li class="menu-item"><%= link_to "FAQ", faq_path %></li>
							<li class="menu-item"><%= link_to "Contact", contact_path %></li>
							<% if signed_in? %>
								<li class="menu-item"><%= link_to "Account", edit_user_path(current_user) %></li>
								<li class="menu-item"><%= link_to "Sign out", signout_path, method: "delete" %></li>
							<% else %>
								<li class="menu-item"><%= link_to "Sign in", signin_path %></li>
							<% end %>
						</ul>
					</div>
					<div class="nav">
						<ul id="menu-main-nav" class="menu">
							<li class="menu-item"><%= link_to "Pre-made Puzzles", word_search_puzzles_path %></li>
							<% if !signed_in? || !current_user.subscription.paid_user? %>
								<li class="menu-item"><%= link_to "Buy Now!", plans_path %></li>
							<% end %>
						</ul>
					</div>
				</div>
				<%= render 'layouts/plans_grid' if is_plans_page %>
				<%= render partial: 'layouts/page_title', 
									 locals: { title: title } unless title.blank? %>
			</div>
		</div>
	</div>
</div>
<!-- div.header end -->

app/views/layouts/_mixpanel.html.erb
<%- if Rails.env.production? -%>
    <!-- start Mixpanel -->
    <script type="text/javascript">
        (function(c,a){window.mixpanel=a;var b,d,h,e;b=c.createElement("script");b.type="text/javascript";b.async=!0;b.src=("https:"===c.location.protocol?"https:":"http:")+'//cdn.mxpnl.com/libs/mixpanel-2.1.min.js';d=c.getElementsByTagName("script")[0];d.parentNode.insertBefore(b,d);a._i=[];a.init=function(b,c,f){function d(a,b){var c=b.split(".");2==c.length&&(a=a[c[0]],b=c[1]);a[b]=function(){a.push([b].concat(Array.prototype.slice.call(arguments,0)))}}var g=a;"undefined"!==typeof f?
g=a[f]=[]:f="mixpanel";g.people=g.people||[];h="disable track track_pageview track_links track_forms register register_once unregister identify name_tag set_config people.identify people.set people.increment".split(" ");for(e=0;e<h.length;e++)d(g,h[e]);a._i.push([b,c,f])};a.__SV=1.1})(document,window.mixpanel||[]);
    mixpanel.init("75c668b4545036a64a1007fc908baf13");
    </script>
    <!-- end Mixpanel -->
<%- else -%>
    <script type='text/javascript'>
    var null_fn = function() {};
    var mpmetrics = {
        track: null_fn,
        track_funnel: null_fn,
        register: null_fn,
        register_once: null_fn,
        register_funnel: null_fn,
        identify: null_fn
    };
    </script>
<%- end -%>

<%- if signed_in? -%>
    <script type="text/javascript">
        $(document).ready( function(){
            mixpanel.name_tag('<%= current_user.email %>');
            mixpanel.people.identify("<%= current_user.email %>");
            mixpanel.people.set({
                        "$first_name": "<%= current_user.first_name %>",
                        "$last_name":"<%= current_user.last_name %>",
                        "$email": "<%= current_user.email %>",
                        "$last_login": new Date(),
                        "$created": "<%= current_user.created_at %>"
            }); 
        });
    </script>
<%- end -%>

app/views/layouts/_page_title.html.erb
<div class="page-title">
	<h2><%= title %></h2>					
</div>

app/views/layouts/_plans_grid.html.erb
<div class="grid col2">
	<div>
		<section>
			<header>
				<hgroup class="top">
					<h1>Trial</h1>
				</hgroup>
				<hgroup class="price">
					<h2><span class="style2">Free</span></h2>
				</hgroup>
			</header>
			<footer>
				<ul>
					<li>
						<strong>15 </strong>Printed Puzzles		
						<div class="tooltip">
							<div>
								<h3>Printed Puzzles</h3>
								<p>
									Every user gets an allowance of puzzles that they can print out.
								</p>
							</div>
						</div>
					</li>
					<li>
						Start Printing Puzzles Immediately! 
					</li>
					<li class="last"><%= link_to "Free Trial", new_word_search_puzzle_path, class: "purchase-btn btn" %></li>
				</ul>
			</footer>
		</section>
		<section class="on">
			<header>
				<hgroup class="top">
					<h1>Teacher</h1>
				</hgroup>
				<hgroup class="price">
					<label>BEST VALUE</label>
					<h2><span class="style1">$</span><span class="style2">29.95</span><span class="style3">Yearly</span></h2>
				</hgroup>
			</header>
			<footer>
				<ul>
					<li>
						<strong>1000 </strong> Printed Puzzles per Year
						<div class="tooltip">
							<div>
								<h3>Printed Puzzles</h3>
								<p>
									Every user gets an allowance of puzzles that they can print out.
								</p>
							</div>
						</div>
					</li>
					<li>
						Start Printing Puzzles Immediately!
					</li>
					<li class="last"><%= link_to "Get Started", purchase_path(plan_id: "swc_teacher"), class: "purchase-btn btn" %></li>
				</ul>
			</footer>
		</section>
	</div>	
</div>	
	<h2 class="purchase-text">
		Start saving time by making puzzles in seconds, for a fraction of the price of activity books.  Easily make high-quality, custom, printable puzzles.
	</h2>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html dir="ltr" lang="en-US">
<head>
	<meta http-equiv="content-type" content="text/html; charset=utf-8">
	<meta name="author" content="Christopher Salvato">
	<meta name="description" content="<%= yield(:meta_description) %>">
	<meta name="keywords" content="<%= yield(:meta_keywords) %>">
	<title><%= yield(:title) %> | Search Word Creator</title>
	<link rel="icon" href="/assets/favicon.ico" />
	<%= stylesheet_link_tag    "application", media: "all" %>
	<% # Turn this javascript include conditional only to be shown on purchase page. %>
	<%= javascript_include_tag "https://js.stripe.com/v1/", "application" %>
	<%= csrf_meta_tags %>
	<%= tag :meta, name: "stripe-key", content: ENV['STRIPE_PUBLISHABLE_KEY'] %>
	<!--[if IE]>
	<script src="js/html5.js" type="text/javascript"></script>
	<![endif]-->
	<!--[if lt IE 9]>
	<link href="css/saas-ie-color.css" rel="stylesheet" type="text/css" media="all" />
	<![endif]-->
	<!--[if lt IE 8]>
	<script src="js/saas-ie7.js" type="text/javascript"></script>
	<![endif]-->
	<%= render 'layouts/google_analytics' %>
	<%= render 'layouts/mixpanel' %>
	<%= yield(:mixpanel_tracking) %>
</head>
<body class="<%= yield(:page_type) %>">
	<%= render partial: 'layouts/header', 
						 locals: { is_plans_page: yield(:page_type) == "page plans",
											 title: yield(:page_title) } %>
	<!-- div start container -->
	<div class="container">
		<div class="center">
			<%= yield :sidebar %>
			<div class="col-main">
				<% flash.each do |key, value| %>
				  <%= content_tag(:div, value, class: "alert alert-#{key}") %>
				<% end %>
				<%= yield %>
			</div>
		</div>
	</div>
	<!--div.container end -->
	<%= render 'layouts/footer' %>
</body>
</html>